In [1]:
import numpy as np
from sklearn.svm import SVC

In [2]:
X = np.array([[0,0],[1,1]])
y = np.array([-1,1])

In [3]:
clf = SVC()

In [4]:
%%capture
clf.fit(X,y)

In [5]:
test = [-0.7, -1]
clf.predict([test])

array([-1])

In [6]:
clf.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [7]:
clf.support_

array([0, 1], dtype=int32)